Q1.  

Total multiplications = n x m x k
Total additions = n x m x (k-1)

In matrix multiplication of (n x k) and (k x m) matrices, each element of each row of matrix-1 is multiplied with each corresponding element of each column of matrix-2. Thus for multiplication of a single row having k elements with single column having k elements has total k multiplications.These k multiplications are added to form a single element in product matrix so there are corresponding k-1 additions here. Now there are m columns in matrix-2, so each row is further multiplied m times, each having k multiplications and k-1 additions. So the number of multiplications and additions for each row of matrix-1 is m x (k) and m x (k-1) respectively. Further, there are n rows so total multiplications will become n*m*k and total additions will be n x m x (k-1).

In [24]:
# Q2. 

list1 = [[1,2,3],[1,0,1]]
list2 = [[1,2],[2,3],[3,0]]

print(f"matrix 1 : \n{list1}")
print(f"matrix  : \n{list2}")

product = []
row = len(list1)
column = len(list2[0])
for i in range(row):
    product.append([])
    for j in range(column):
        value=0
        for k in range(3):
            value = value + list1[i][k]*list2[k][j]
        product[i].append(value)
print(f"Product matrix without using numpy : {product}\n")


# =>  Matrix Multiplication using Numpy :

print("=>  Matrix Multiplication using Numpy :\n")
import numpy as np
m1 = np.array([[1,2,3],[1,0,1]])
m2 = np.array([[1,2],[2,3],[3,0]])
print(f"matrix 1 : \n{m1}")
print(f"matrix 2 : \n{m2}")
product_by_numpy = m1.dot(m2)
print(f"Product by numpy : \n{product_by_numpy}")

matrix 1 : 
[[1, 2, 3], [1, 0, 1]]
matrix  : 
[[1, 2], [2, 3], [3, 0]]
Product matrix without using numpy : [[14, 8], [4, 2]]

=>  Matrix Multiplication using Numpy :

matrix 1 : 
[[1 2 3]
 [1 0 1]]
matrix 2 : 
[[1 2]
 [2 3]
 [3 0]]
Product by numpy : 
[[14  8]
 [ 4  2]]


Q4. 

Gradient of $f(x,y) = x^2y + y^3sin(x)$ with respect to $x = \frac{\partial f}{\partial x} = 2xy + y^3cos(x)$ .\
Gradient of $f(x,y) = x^2y + y^3sin(x)$ with respect to $y = \frac{\partial f}{\partial y} = x^2 + 3y^2sin(x)$ .

In [29]:
# Q7 

Dict = {
    2022 : {
        'BE': {
            'Roll_no' : 202120000,
            'Name' : 'ABC',
            'Marks' : {
                'Maths':89,
                'English': 75,
                'Science': 82
            }
        },
        'CSE': {
            'Roll_no' : 202120001,
            'Name' : 'AVF',
            'Marks' : {
                'Maths':88,
                'English': 85,
                'Science': 72
            }
        }
    },
        
    2023 : {
        'ME': {
            'Roll_no' : 202120002,
            'Name' : 'DEF',
            'Marks' : {
                'Maths':76,
                'English': 56,
                'Science': 77
            }
        },
        'CSE': {
            'Roll_no' : 20212003,
            'Name' : 'VMS',
            'Marks' : {
                'Maths':33,
                'English': 67,
                'Science': 56
            }
        }
    },
        
    2024 : {
        'CE': {
            'Roll_no' : 202120004,
            'Name' : 'ABC',
            'Marks' : {
                'Maths':89,
                'English': 75,
                'Science': 82
            }
        },
        'CSE': {
            'Roll_no' : 202120005,
            'Name' : 'AVF',
            'Marks' : {
                'Maths':98,
                'English': 89,
                'Science': 99
            }
        }
    },
        
    2025 : {
        'BE': {
            'Roll_no' : 202120008,
            'Name' : 'XYZ',
            'Marks' : {
                'Maths':86,
                'English': 79,
                'Science': 83
            }
        },
        'EE': {
            'Roll_no' : 202120009,
            'Name' : 'PQR',
            'Marks' : {
                'Maths':76,
                'English': 85,
                'Science': 79
            }
        }
    }   
    
}

print(Dict)

{2022: {'BE': {'Roll_no': 202120000, 'Name': 'ABC', 'Marks': {'Maths': 89, 'English': 75, 'Science': 82}}, 'CSE': {'Roll_no': 202120001, 'Name': 'AVF', 'Marks': {'Maths': 88, 'English': 85, 'Science': 72}}}, 2023: {'ME': {'Roll_no': 202120002, 'Name': 'DEF', 'Marks': {'Maths': 76, 'English': 56, 'Science': 77}}, 'CSE': {'Roll_no': 20212003, 'Name': 'VMS', 'Marks': {'Maths': 33, 'English': 67, 'Science': 56}}}, 2024: {'CE': {'Roll_no': 202120004, 'Name': 'ABC', 'Marks': {'Maths': 89, 'English': 75, 'Science': 82}}, 'CSE': {'Roll_no': 202120005, 'Name': 'AVF', 'Marks': {'Maths': 98, 'English': 89, 'Science': 99}}}, 2025: {'BE': {'Roll_no': 202120008, 'Name': 'XYZ', 'Marks': {'Maths': 86, 'English': 79, 'Science': 83}}, 'EE': {'Roll_no': 202120009, 'Name': 'PQR', 'Marks': {'Maths': 76, 'English': 85, 'Science': 79}}}}
